apiVersion: apps/v1
kind: Deployment
metadata:
  name: sort-master
spec:
  selector:
    matchLabels:
      app: sort-master
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: sort-master
    spec:
      containers:
      - name: sort-master
        image: 192.168.99.100:80/batch-gemfire-file-sort-master
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.application.name
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.datasource.driverClassName
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.datasource.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.datasource.password
        - name: SPRING_BATCH_INITIALIZESCHEMA
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.batch.initialize-schema
        - name: SPRING_BATCH_JOB_ENABLED
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.batch.job.enabled
        - name: AMAZONPROPERTIES_ENDPOINTURL
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: amazonProperties.endpointUrl
        - name: AMAZONPROPERTIES_ACCESSKEY
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: amazonProperties.accessKey
        - name: AMAZONPROPERTIES_SECRETKEY
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: amazonProperties.secretKey
        - name: AMAZONPROPERTIES_BUCKETNAME
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: amazonProperties.bucketName
        - name: SPRING_BATCH_GRIDSIZE
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.batch.grid-size
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.rabbitmq.host
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.rabbitmq.username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sort-master-config
              key: spring.rabbitmq.password
